name: pymc
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - absl-py=0.7.1=py37_0
  - appdirs=1.4.3=py_1
  - atomicwrites=1.3.0=py_0
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py_0
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_8
  - black=19.3b0=py_0
  - bleach=3.1.0=py_0
  - bzip2=1.0.8=h516909a_0
  - ca-certificates=2019.6.16=hecc5488_0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2019.6.16=py37_1
  - cffi=1.12.3=py37h8022711_0
  - cftime=1.0.3.4=py37hd352d35_1001
  - click=7.0=py_0
  - coverage=4.5.4=py37h516909a_0
  - curl=7.65.3=hf8cf82a_0
  - cycler=0.10.0=py_1
  - dbus=1.13.6=he372182_0
  - decorator=4.4.0=py_0
  - defusedxml=0.5.0=py_1
  - entrypoints=0.3=py37_1000
  - expat=2.2.5=he1b5a44_1003
  - fastcache=1.1.0=py37h516909a_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - fribidi=1.0.5=h516909a_1002
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_8
  - gettext=0.19.8.1=hc5be6a0_1002
  - gf2x=1.2=ha03fbb7_1003
  - glib=2.58.3=h6f030ca_1002
  - gmp=6.1.2=hf484d3e_1000
  - gmpy2=2.1.0b1=py37h04dde30_0
  - graphite2=1.3.13=hf484d3e_1000
  - graphviz=2.40.1=h5933667_1
  - greenlet=0.4.15=py37h516909a_0
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_8
  - h5py=2.9.0=nompi_py37h513d04c_1104
  - harfbuzz=2.4.0=h9f30f68_2
  - hdf4=4.2.13=h9a582f1_1002
  - hdf5=1.10.5=nompi_h3c11f04_1103
  - hypothesis=4.33.1=py37_0
  - icu=64.2=he1b5a44_0
  - importlib_metadata=0.18=py37_0
  - intel-openmp=2019.4=243
  - ipykernel=5.1.2=py37h5ca1d4c_0
  - ipython=7.7.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - jax=0.1.41=pyh5ca1d4c_0
  - jaxlib=0.1.22=py37h5ca1d4c_0
  - jedi=0.15.1=py37_0
  - jinja2=2.10.1=py_0
  - joblib=0.13.2=py_0
  - jpeg=9c=h14c3975_1001
  - json5=0.8.5=py_0
  - jsonschema=3.0.2=py37_0
  - jupyter_client=5.3.1=py_0
  - jupyter_core=4.4.0=py_0
  - jupyterlab=1.0.9=py37_0
  - jupyterlab_server=1.0.6=py_0
  - kiwisolver=1.1.0=py37hc9558a2_0
  - krb5=1.16.3=h05b26f9_1001
  - libblas=3.8.0=10_mkl
  - libcblas=3.8.0=10_mkl
  - libcurl=7.65.3=hda55be3_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libflint=2.5.2=heb735ee_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgpuarray=0.7.6=h14c3975_1003
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=10_mkl
  - libnetcdf=4.6.2=h056eaf5_1002
  - libpng=1.6.37=hed695b0_0
  - libprotobuf=3.9.1=h8b12597_0
  - libsodium=1.0.17=h516909a_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h57b8799_1003
  - libtool=2.4.6=h14c3975_1002
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=hee79883_2
  - llvmlite=0.29.0=py37hfd453ef_1
  - lz4-c=1.8.3=he1b5a44_1001
  - mako=1.1.0=py_0
  - markupsafe=1.1.1=py37h14c3975_0
  - matplotlib=3.1.1=py37_1
  - matplotlib-base=3.1.1=py37he7580a8_1
  - metis=5.1.0=hf484d3e_1003
  - mistune=0.8.4=py37h14c3975_1000
  - mkl=2019.4=243
  - mkl-service=2.2.0=py37h516909a_0
  - more-itertools=7.2.0=py_0
  - mpc=1.1.0=hb20f59a_1006
  - mpfr=4.0.2=ha14ba45_0
  - mpmath=1.1.0=py_0
  - msgpack-python=0.6.1=py37h6bb024c_0
  - mypy=0.720=py_0
  - mypy_extensions=0.4.1=py37_1000
  - nbconvert=5.6.0=py_0
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hf484d3e_1002
  - neovim=0.3.1=py37_0
  - netcdf4=1.5.1.2=py37h73a1b54_1
  - networkx=2.3=py_0
  - notebook=6.0.0=py37_0
  - ntl=10.3.0=1
  - numba=0.45.1=py37hb3f55d8_0
  - numpy=1.17.0=py37h95a1406_0
  - openssl=1.1.1c=h516909a_0
  - opt_einsum=3.0.0=py_0
  - packaging=19.0=py_0
  - pandas=0.25.0=py37hb3f55d8_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - pango=1.42.4=ha030887_1
  - parso=0.5.1=py_0
  - patsy=0.5.1=py_0
  - pcre=8.41=hf484d3e_1003
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_1000
  - pip=19.2.2=py37_0
  - pixman=0.38.0=h516909a_1003
  - pkg-config=0.29.2=h14c3975_1005
  - pluggy=0.12.0=py_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py_0
  - protobuf=3.9.1=py37he1b5a44_0
  - psutil=5.6.3=py37h516909a_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - py=1.8.0=py_0
  - pycparser=2.19=py37_1
  - pydoe2=1.2.1=py_0
  - pygments=2.4.2=py_0
  - pygpu=0.7.6=py37h3010b51_1000
  - pympler=0.7=py_0
  - pynvim=0.3.2=py37_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py37hcca6a23_2
  - pyrsistent=0.15.4=py37h516909a_0
  - pytest=5.1.1=py37_0
  - python=3.7.3=h33d41f4_1
  - python-dateutil=2.8.0=py_0
  - python-graphviz=0.11.1=py_1
  - python-symengine=0.4.0=py37h9603a25_0
  - pytz=2019.2=py_0
  - pywavelets=1.0.3=py37hd352d35_1
  - pyzmq=18.0.2=py37h1768529_2
  - qt=5.9.7=h0c104cb_3
  - readline=8.0=hf8c457e_0
  - scikit-learn=0.21.3=py37hcdab131_0
  - scipy=1.3.1=py37h921218d_2
  - seaborn=0.9.0=py_1
  - send2trash=1.5.0=py_0
  - setuptools=41.2.0=py37_0
  - sip=4.19.8=py37hf484d3e_1000
  - six=1.12.0=py37_1000
  - smt=0.3.4=py37hb3f55d8_0
  - sqlite=3.29.0=hcee41ef_0
  - statsmodels=0.10.1=py37hc1659b7_0
  - suitesparse=4.5.6=heab0a99_1202
  - sundials=4.1.0=h775d46b_1
  - symengine=0.4.1=h9603a25_0
  - sympy=1.4=py37_0
  - tbb=2019.7=hc9558a2_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py_1001
  - tk=8.6.9=hed695b0_1002
  - toml=0.10.0=py_0
  - tornado=6.0.3=py37h516909a_0
  - tqdm=4.34.0=py_0
  - traitlets=4.3.2=py37_1000
  - typed-ast=1.4.0=py37h516909a_0
  - typing_extensions=3.7.4=py37_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.6=py37_0
  - xarray=0.12.3=py_0
  - xz=5.2.4=h14c3975_1001
  - zeromq=4.3.2=he1b5a44_2
  - zipp=0.5.2=py_0
  - zlib=1.2.11=h516909a_1005
  - zstd=1.4.0=h3b9ef0a_0
  - pip:
    - astor==0.8.0

